export const REQUIRED_COMPUTED_STYLES = [
  'display',
  'visibility',
  'opacity',
  'overflow',
  'overflow-x',
  'overflow-y',
  'cursor',
  'pointer-events',
  'position',
  'background-color',
] as const;

export const DISABLED_ELEMENTS = new Set([
  'style',
  'script',
  'head',
  'meta',
  'link',
  'title',
  'noscript',
  'template',
]);

export const SVG_ELEMENTS = new Set([
  'path',
  'rect',
  'g',
  'circle',
  'ellipse',
  'line',
  'polyline',
  'polygon',
  'use',
  'defs',
  'clipPath',
  'mask',
  'pattern',
  'image',
  'text',
  'tspan',
  'linearGradient',
  'radialGradient',
  'stop',
  'symbol',
  'marker',
  'filter',
  'feGaussianBlur',
  'feOffset',
  'feMerge',
  'feMergeNode',
]);

export const DEFAULT_INCLUDE_ATTRIBUTES = [
  'title',
  'type',
  'checked',
  'id',
  'name',
  'role',
  'value',
  'placeholder',
  'data-date-format',
  'alt',
  'aria-label',
  'aria-expanded',
  'data-state',
  'aria-checked',
  'aria-valuemin',
  'aria-valuemax',
  'aria-valuenow',
  'aria-placeholder',
  'pattern',
  'min',
  'max',
  'minlength',
  'maxlength',
  'step',
  'accept',
  'multiple',
  'inputmode',
  'autocomplete',
  'format',
  'expected_format',
  'contenteditable',
  'pseudo',
  'selected',
  'expanded',
  'pressed',
  'disabled',
  'invalid',
  'valuemin',
  'valuemax',
  'valuenow',
  'keyshortcuts',
  'haspopup',
  'multiselectable',
  'required',
  'valuetext',
  'level',
  'busy',
  'live',
  'ax_name',
  'href',
  'src',
  'action',
  'method',
  'for',
  'data-testid',
  'data-test-id',
] as const;

export const INTERACTIVE_TAGS = new Set([
  'button',
  'input',
  'select',
  'textarea',
  'a',
  'details',
  'summary',
  'option',
  'optgroup',
]);

export const INTERACTIVE_ROLES = new Set([
  'button',
  'link',
  'menuitem',
  'option',
  'radio',
  'checkbox',
  'tab',
  'textbox',
  'combobox',
  'slider',
  'spinbutton',
  'search',
  'searchbox',
  'listbox',
  'menu',
  'menubar',
  'tree',
  'grid',
  'treegrid',
  'switch',
  'progressbar',
  'scrollbar',
]);

export const INTERACTIVE_ATTRIBUTES = new Set([
  'onclick',
  'onmousedown',
  'onmouseup',
  'onkeydown',
  'onkeyup',
  'tabindex',
  'ng-click',
  '@click',
  'v-on:click',
]);

export const INTERACTIVE_AX_PROPERTIES = new Set([
  'focusable',
  'editable',
  'settable',
  'checked',
  'expanded',
  'pressed',
  'selected',
  'required',
  'autocomplete',
]);

export const SCROLLABLE_TAGS = new Set([
  'div',
  'main',
  'section',
  'article',
  'aside',
  'body',
  'html',
  'nav',
  'ul',
  'ol',
  'pre',
  'code',
]);

export const INPUT_FORMAT_HINTS: Record<string, string> = {
  date: 'YYYY-MM-DD',
  time: 'HH:MM',
  'datetime-local': 'YYYY-MM-DDTHH:MM',
  month: 'YYYY-MM',
  week: 'YYYY-W##',
};

export const SEARCH_INDICATORS = new Set([
  'search',
  'magnify',
  'glass',
  'lookup',
  'find',
  'query',
  'search-icon',
  'search-btn',
  'search-button',
  'searchbox',
]);
