export interface HistoryEntry {
  id: string;
  url: string;
  title: string;
  visitTime: number;
  visitCount: number;
  lastVisitTime: number;
  favicon?: string;
  typedCount: number; // How many times user typed this URL
  transition: HistoryTransition;
}

export enum HistoryTransition {
  LINK = 'link',           // User clicked a link
  TYPED = 'typed',         // User typed URL in address bar
  AUTO_BOOKMARK = 'auto_bookmark', // Auto-generated bookmark
  AUTO_SUBFRAME = 'auto_subframe', // Subframe navigation
  MANUAL_SUBFRAME = 'manual_subframe', // Manual subframe navigation
  GENERATED = 'generated', // Generated by browser
  RELOAD = 'reload',       // Page reload
  KEYWORD = 'keyword',     // Keyword search
  FORM_SUBMIT = 'form_submit', // Form submission
}

export interface HistoryQuery {
  text?: string;           // Search text
  startTime?: number;      // Start timestamp
  endTime?: number;        // End timestamp
  maxResults?: number;     // Maximum results to return
}

export interface HistoryStats {
  totalEntries: number;
  totalVisits: number;
  topDomains: Array<{ domain: string; count: number }>;
  todayVisits: number;
  weekVisits: number;
}

export enum AutocompleteSuggestionType {
  HISTORY = 'history',           // From browsing history
  SEARCH = 'search',             // Search suggestion from Google
  URL = 'url',                   // Direct URL navigation
}

export interface AutocompleteSuggestion {
  id: string;
  type: AutocompleteSuggestionType;
  title: string;
  url: string;
  subtitle?: string;             // Additional context (e.g., domain for history)
  favicon?: string;
  visitCount?: number;           // For history items
  relevanceScore?: number;       // For sorting
}