name: Build Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv openai anthropic nltk
          
      - name: Download NLTK data
        run: |
          python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('punkt_tab')"
          
      - name: Install Node.js dependencies
        run: npm ci
        
      - name: Prepare Python bundle
        run: npm run prebuild
        
      - name: Test build (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
        
      - name: Test build (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux
        
      - name: Test build (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run build:win 